language: rust
cache: cargo
dist: trusty
sudo: true
rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake

env:
  global:
    - RUST_BACKTRACE="1"
  matrix:
    - TEST_DIR=.

script: 
- cd $TEST_DIR && RUST_TEST_THREADS=1 cargo test --verbose on_commit
- cd $TEST_DIR && cargo test --doc 
