[package]
name = "cuckoo_miner"
version = "0.1.0"
authors = ["yeastplume"]

[workspace]
members = ["miner","cuckoo-sys", "config"]

[dependencies]
miner = { path = "miner", version="0.1.0" }
config = { path = "config", version="0.1.0" }

env_logger="^0.3.5"
log = "^0.3"



