[package]
name = "cuckoo-miner"
version = "0.1.0"
authors = ["yeastplume"]

[workspace]
members = ["cuckoo-miner","cuckoo-sys"]

[dependencies]
cuckoo_miner = { path = "cuckoo-miner" }

env_logger="^0.3.5"
log = "^0.3"



