[package]
name = "common"
version = "0.1.0"
authors = ["yeastplume"]
license = "MIT/Apache-2.0/BSD-3-Clause"
description = "Cuckoo Common Build Tools"
readme = "README.md"

[dependencies]
gcc = "0.3.51"

[dev-dependencies]
const-cstr = "0.2"

[build-dependencies]
make-cmd = "0.1"
